name = "TwoLoopSunriseFeynmanIntegrals"
uuid = "b98f81b4-cfb0-40f2-a783-f83e48215178"
authors = ["Wen-Di Li", "Quan-feng WU <wuquanfeng@ihep.ac.cn>"]
version = "0.1.0"

[deps]
FORM_jll = "f4eadb04-70c1-5b36-8221-785c072cda07"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
