name: Prepare ν list
on:
  push:
    branches:
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  generate_nu_list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      # Comment out the following lines for the next update of julia-actions/julia-runtest
      # - uses: julia-actions/julia-runtest@v1
      #   with: 
      #     test_args: |
      #       --test-type=random-ν-list
      #       --
      #       -n=100
      #       -o=random-ν-list.jld2
      - name: Generate ν list
        run: julia --project -e "using Pkg; Pkg.test(test_args=[\"--test-type=random-ν-list\", \"--\", \"-n=100\", \"--max-ν=5\", \"-o=${{ github.WORKSPACE }}/random-ν-list.jld2\"])"

      - uses: actions/upload-artifact@v4
        with:
          name: ν_list
          path: ${{ github.WORKSPACE }}/random-ν-list.jld2
